name: self-test
on:
  workflow_dispatch: {}
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this action repo
        uses: actions/checkout@v5

      - name: Prepare dummy workdir
        run: |
          mkdir -p target
          cat > target/go.mod <<'EOF'
          module dummy
          go 1.25
          require github.com/sirupsen/logrus v1.9.0
          EOF

      - name: Run local action (mode=go)
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mode: go
          workdir: target
          verbose: true
          min_score: "70"

      - name: Inspect workspace
        run: |
          echo "PWD: $(pwd)" && ls -la
          echo "--- target ---" && ls -la target || true

      - name: Verify output
        run: |
          test -s target/stay_or_go_report.tsv
          echo "---- HEAD ----"
          head -n 20 target/stay_or_go_report.tsv || true
          echo "--------------"

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: stay_or_go_report_tsv
          path: target/stay_or_go_report.tsv
